"""Centralized application settings using Pydantic BaseSettings.

All configuration is loaded from environment variables and .env file.
Never hardcode credentials—use this module for all settings access.

Example:
    >>> from src.config.settings import settings
    >>> print(settings.DATABASE_URL)
"""

from __future__ import annotations

from functools import lru_cache
from typing import List

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    """Application-wide settings loaded from environment variables.

    Attributes:
        APP_NAME: Human-readable application name.
        APP_VERSION: Semantic version string.
        ENVIRONMENT: Runtime environment ('development' | 'production' | 'test').
        DEBUG: Enable FastAPI debug mode. Automatically False outside development.

        DATABASE_URL: Full asyncpg-compatible PostgreSQL connection URL.
        DB_SSL_MODE: SSL behaviour ('require' | 'insecure' | 'disable').

        REDIS_URL: Redis connection URL.
        SECRET_KEY: Application secret key for signing tokens / sessions.
        ALLOWED_ORIGINS_STR: Comma-separated list of CORS allowed origins.

        DATA_PATH: Root directory for raw and processed data files.
        MODELS_PATH: Root directory for trained model artefacts (.pkl, .pt).
        RAW_STEAM_DATA_PATH: Absolute or relative path to the raw Steam games CSV.
        IMPUTED_DATA_PATH: Path to the KS-validated imputed CSV generated by the pipeline.

        SUPABASE_URL: Optional Supabase project URL (leave empty for local PG).
        SUPABASE_KEY: Optional Supabase anon/service key.

        TEST_DB_HOST: Hostname used by supabase auth smoke tests.
        TEST_DB_PORT: Port used by supabase auth smoke tests.
        TEST_DB_USER: User used by supabase auth smoke tests.
        TEST_DB_PASSWORD: Password used by supabase auth smoke tests.
        TEST_DB_NAME: DB name used by supabase auth smoke tests.
    """

    # ── Application ──────────────────────────────────────────────────────────
    APP_NAME: str = "Killswitch Engage"
    APP_VERSION: str = "1.0.0"
    ENVIRONMENT: str = "development"

    @property
    def DEBUG(self) -> bool:  # noqa: N802 (property masking class attr)
        """True only in development environment."""
        return self.ENVIRONMENT == "development"

    # ── Database ──────────────────────────────────────────────────────────────
    DATABASE_URL: str = "postgresql://postgres:postgres@localhost:5432/steam_db"
    DB_SSL_MODE: str = "require"

    # ── Cache ─────────────────────────────────────────────────────────────────
    REDIS_URL: str = "redis://localhost:6379/0"

    # ── Security ──────────────────────────────────────────────────────────────
    SECRET_KEY: str = "troque-esta-chave-em-producao"

    # ── CORS ──────────────────────────────────────────────────────────────────
    ALLOWED_ORIGINS_STR: str = "http://localhost:3000,http://localhost:8000"

    @property
    def ALLOWED_ORIGINS(self) -> List[str]:  # noqa: N802
        """Parsed list of allowed CORS origins."""
        return [o.strip() for o in self.ALLOWED_ORIGINS_STR.split(",") if o.strip()]

    # ── Paths ─────────────────────────────────────────────────────────────────
    DATA_PATH: str = "data/"
    MODELS_PATH: str = "models/"
    RAW_STEAM_DATA_PATH: str = "data/raw/games.csv"
    IMPUTED_DATA_PATH: str = "data/processed/imputed_dataset_v2.csv"

    # ── Supabase (optional) ───────────────────────────────────────────────────
    SUPABASE_URL: str = ""
    SUPABASE_KEY: str = ""

    # ── Smoke-test DB (src/validation/test_supabase_auth.py) ─────────────────
    TEST_DB_HOST: str = ""
    TEST_DB_PORT: int = 6543
    TEST_DB_USER: str = ""
    TEST_DB_PASSWORD: str = ""
    TEST_DB_NAME: str = "postgres"

    model_config = {
        "env_file": ".env",
        "env_file_encoding": "utf-8",
        "extra": "ignore",
    }


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return the cached application settings singleton.

    Returns:
        Settings: The application settings instance.
    """
    return Settings()


# Module-level singleton for convenient imports:
#   from src.config.settings import settings
settings: Settings = get_settings()
